[package]
name = "extension-op"
version = "0.5.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

auto-diff = { path="../auto-diff", version = "0.5.7"}
auto-diff-macros = { path="../macros", version = "0.5.7" }
